"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TokenIntent:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TokenIntentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TokenIntent.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOGGER: _TokenIntent.ValueType  # 0
    FRONTEND: _TokenIntent.ValueType  # 1

class TokenIntent(_TokenIntent, metaclass=_TokenIntentEnumTypeWrapper): ...

LOGGER: TokenIntent.ValueType  # 0
FRONTEND: TokenIntent.ValueType  # 1
global___TokenIntent = TokenIntent

class _VerifyTokenRequestResultEnum:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VerifyTokenRequestResultEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VerifyTokenRequestResultEnum.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNAUTHORISED: _VerifyTokenRequestResultEnum.ValueType  # 0
    NOTFOUND: _VerifyTokenRequestResultEnum.ValueType  # 1
    AUTHORISED: _VerifyTokenRequestResultEnum.ValueType  # 2

class VerifyTokenRequestResultEnum(_VerifyTokenRequestResultEnum, metaclass=_VerifyTokenRequestResultEnumEnumTypeWrapper): ...

UNAUTHORISED: VerifyTokenRequestResultEnum.ValueType  # 0
NOTFOUND: VerifyTokenRequestResultEnum.ValueType  # 1
AUTHORISED: VerifyTokenRequestResultEnum.ValueType  # 2
global___VerifyTokenRequestResultEnum = VerifyTokenRequestResultEnum

class _GenerateTokenRequestResultEnum:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenerateTokenRequestResultEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GenerateTokenRequestResultEnum.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NAME_ALREADY_EXISTS: _GenerateTokenRequestResultEnum.ValueType  # 0
    """If another token under this name is already present."""
    TOKEN_ALREADY_EXISTS: _GenerateTokenRequestResultEnum.ValueType  # 1
    """If the exact token is already present."""
    TOKEN_GENERATION_SUCCEEDED: _GenerateTokenRequestResultEnum.ValueType  # 2
    """If the token was successfully added."""

class GenerateTokenRequestResultEnum(_GenerateTokenRequestResultEnum, metaclass=_GenerateTokenRequestResultEnumEnumTypeWrapper): ...

NAME_ALREADY_EXISTS: GenerateTokenRequestResultEnum.ValueType  # 0
"""If another token under this name is already present."""
TOKEN_ALREADY_EXISTS: GenerateTokenRequestResultEnum.ValueType  # 1
"""If the exact token is already present."""
TOKEN_GENERATION_SUCCEEDED: GenerateTokenRequestResultEnum.ValueType  # 2
"""If the token was successfully added."""
global___GenerateTokenRequestResultEnum = GenerateTokenRequestResultEnum

class _RevokeTokenRequestResultEnum:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RevokeTokenRequestResultEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RevokeTokenRequestResultEnum.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TOKEN_NOT_FOUND: _RevokeTokenRequestResultEnum.ValueType  # 0
    """If the token is not found."""
    TOKEN_REVOKATION_SUCCEEDED: _RevokeTokenRequestResultEnum.ValueType  # 1
    """If the token was successfully added."""

class RevokeTokenRequestResultEnum(_RevokeTokenRequestResultEnum, metaclass=_RevokeTokenRequestResultEnumEnumTypeWrapper): ...

TOKEN_NOT_FOUND: RevokeTokenRequestResultEnum.ValueType  # 0
"""If the token is not found."""
TOKEN_REVOKATION_SUCCEEDED: RevokeTokenRequestResultEnum.ValueType  # 1
"""If the token was successfully added."""
global___RevokeTokenRequestResultEnum = RevokeTokenRequestResultEnum

@typing_extensions.final
class Name(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INNER_FIELD_NUMBER: builtins.int
    inner: builtins.str
    def __init__(
        self,
        *,
        inner: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["inner", b"inner"]) -> None: ...

global___Name = Name

@typing_extensions.final
class TokenPermissions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READ_FIELD_NUMBER: builtins.int
    WRITE_FIELD_NUMBER: builtins.int
    read: builtins.bool
    write: builtins.bool
    def __init__(
        self,
        *,
        read: builtins.bool = ...,
        write: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["read", b"read", "write", b"write"]) -> None: ...

global___TokenPermissions = TokenPermissions

@typing_extensions.final
class Token(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PERMISSIONS_FIELD_NUMBER: builtins.int
    INTENT_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> global___Name: ...
    @property
    def permissions(self) -> global___TokenPermissions: ...
    intent: global___TokenIntent.ValueType
    def __init__(
        self,
        *,
        name: global___Name | None = ...,
        permissions: global___TokenPermissions | None = ...,
        intent: global___TokenIntent.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name", b"name", "permissions", b"permissions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["intent", b"intent", "name", b"name", "permissions", b"permissions"]) -> None: ...

global___Token = Token

@typing_extensions.final
class GenerateTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    INTENT_FIELD_NUMBER: builtins.int
    @property
    def name(self) -> global___Name: ...
    intent: global___TokenIntent.ValueType
    def __init__(
        self,
        *,
        name: global___Name | None = ...,
        intent: global___TokenIntent.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["intent", b"intent", "name", b"name"]) -> None: ...

global___GenerateTokenRequest = GenerateTokenRequest

@typing_extensions.final
class VerifyTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    INTENT_FIELD_NUMBER: builtins.int
    @property
    def token(self) -> global___Token: ...
    intent: global___TokenIntent.ValueType
    def __init__(
        self,
        *,
        token: global___Token | None = ...,
        intent: global___TokenIntent.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["intent", b"intent", "token", b"token"]) -> None: ...

global___VerifyTokenRequest = VerifyTokenRequest

@typing_extensions.final
class VerifyTokenRequestResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    message: builtins.str
    status: global___VerifyTokenRequestResultEnum.ValueType
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        status: global___VerifyTokenRequestResultEnum.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "status", b"status"]) -> None: ...

global___VerifyTokenRequestResult = VerifyTokenRequestResult

@typing_extensions.final
class RevokeTokenRequestResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    message: builtins.str
    status: global___RevokeTokenRequestResultEnum.ValueType
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        status: global___RevokeTokenRequestResultEnum.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "status", b"status"]) -> None: ...

global___RevokeTokenRequestResult = RevokeTokenRequestResult

@typing_extensions.final
class GenerateTokenRequestResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    status: global___GenerateTokenRequestResultEnum.ValueType
    @property
    def token(self) -> global___Token: ...
    def __init__(
        self,
        *,
        status: global___GenerateTokenRequestResultEnum.ValueType = ...,
        token: global___Token | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_token", b"_token", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_token", b"_token", "status", b"status", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_token", b"_token"]) -> typing_extensions.Literal["token"] | None: ...

global___GenerateTokenRequestResult = GenerateTokenRequestResult

@typing_extensions.final
class LoginUrl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["url", b"url"]) -> None: ...

global___LoginUrl = LoginUrl
