# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtrace_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61\x63ktrace_data.proto\x12\x1c\x63odectrl.data.backtrace_data\"g\n\rBacktraceData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\x12\x12\n\nlineNumber\x18\x03 \x01(\r\x12\x14\n\x0c\x63olumnNumber\x18\x04 \x01(\r\x12\x0c\n\x04\x63ode\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtrace_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKTRACEDATA._serialized_start=54
  _BACKTRACEDATA._serialized_end=157
# @@protoc_insertion_point(module_scope)
