"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BacktraceData(google.protobuf.message.Message):
    """Generalised message containing information regarding a single stacktrace
    item.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FILEPATH_FIELD_NUMBER: builtins.int
    LINENUMBER_FIELD_NUMBER: builtins.int
    COLUMNNUMBER_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    name: builtins.str
    filePath: builtins.str
    lineNumber: builtins.int
    columnNumber: builtins.int
    code: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        filePath: builtins.str = ...,
        lineNumber: builtins.int = ...,
        columnNumber: builtins.int = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "columnNumber", b"columnNumber", "filePath", b"filePath", "lineNumber", b"lineNumber", "name", b"name"]) -> None: ...

global___BacktraceData = BacktraceData
