"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import backtrace_data_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Log(google.protobuf.message.Message):
    """Main log message for use when sending to a CodeCtrl gRPC server."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CodeSnippetEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    UUID_FIELD_NUMBER: builtins.int
    STACK_FIELD_NUMBER: builtins.int
    LINENUMBER_FIELD_NUMBER: builtins.int
    CODESNIPPET_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    MESSAGETYPE_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    WARNINGS_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    """NOTE: This field should be generated by CodeCtrl gRPC servers, any value
    assigned to it by loggers will be overwritten. Therefore, leave it as a
    blank.
    """
    @property
    def stack(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[backtrace_data_pb2.BacktraceData]: ...
    lineNumber: builtins.int
    @property
    def codeSnippet(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.str]: ...
    message: builtins.str
    messageType: builtins.str
    fileName: builtins.str
    address: builtins.str
    """NOTE: This field should be generated by CodeCtrl gRPC servers, any value
    assigned to it by loggers will be overwritten. Therefore, leave it as a
    blank.
    """
    language: builtins.str
    @property
    def warnings(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
        stack: collections.abc.Iterable[backtrace_data_pb2.BacktraceData] | None = ...,
        lineNumber: builtins.int = ...,
        codeSnippet: collections.abc.Mapping[builtins.int, builtins.str] | None = ...,
        message: builtins.str = ...,
        messageType: builtins.str = ...,
        fileName: builtins.str = ...,
        address: builtins.str = ...,
        language: builtins.str = ...,
        warnings: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "codeSnippet", b"codeSnippet", "fileName", b"fileName", "language", b"language", "lineNumber", b"lineNumber", "message", b"message", "messageType", b"messageType", "stack", b"stack", "uuid", b"uuid", "warnings", b"warnings"]) -> None: ...

global___Log = Log
