# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import backtrace_data_pb2 as backtrace__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x11\x63odectrl.data.log\x1a\x14\x62\x61\x63ktrace_data.proto\"\xc2\x02\n\x03Log\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12:\n\x05stack\x18\x02 \x03(\x0b\x32+.codectrl.data.backtrace_data.BacktraceData\x12\x12\n\nlineNumber\x18\x03 \x01(\r\x12<\n\x0b\x63odeSnippet\x18\x04 \x03(\x0b\x32\'.codectrl.data.log.Log.CodeSnippetEntry\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x13\n\x0bmessageType\x18\x06 \x01(\t\x12\x10\n\x08\x66ileName\x18\x07 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x08 \x01(\t\x12\x10\n\x08language\x18\t \x01(\t\x12\x10\n\x08warnings\x18\n \x03(\t\x1a\x32\n\x10\x43odeSnippetEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOG_CODESNIPPETENTRY._options = None
  _LOG_CODESNIPPETENTRY._serialized_options = b'8\001'
  _LOG._serialized_start=55
  _LOG._serialized_end=377
  _LOG_CODESNIPPETENTRY._serialized_start=327
  _LOG_CODESNIPPETENTRY._serialized_end=377
# @@protoc_insertion_point(module_scope)
